MNT: Re-rendered with conda-smithy 3.1.12 and pinning 2018.10.16

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -4,39 +4,62 @@
 language: generic
 
 os: osx
-osx_image: beta-xcode6.1
+osx_image: xcode6.4
 
 env:
   matrix:
-    
-    - CONDA_PY=27
-    - CONDA_PY=34
-    - CONDA_PY=35
+    - CONFIG=osx_python2.7
+    - CONFIG=osx_python3.6
+    - CONFIG=osx_python3.7
+
   global:
     # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
     - secure: "WCX8HhBvPhcsUnSnLRja53a8fmaMu5K/NnH/RQH5y5pPNHdH00KZs8dB3B/+QtorOMr5khvhqc0s07EJb58zmyccIy7lsdXGK0oYG8mhQE1lid0YE/Qs+d3qIfdMy97+pYklZB+kv8gLBVf4jmugPkwrYfZpHmfNL4GFUA7wFCkTLdQCZWalAvK2cw+0382f4I0cGcsIuSA4ictzeQB8KErIoHqlnFm39OpixcYrQAG8DeQYvmMW6J+zPMGu5XSzHCe+29eURryXXi1Mg8MLgqMJMXCBrhSxfqmgQ3ZcQkI8T8CYIIg/r/OVXf4RdgG/VloABXoCpV3bDzUOpzybLp5FdfUckCXaggB9qafso0MAmH/SZOaQNPnsCF8A5PWcA9N5k/XWDQP/nNKlFOSMSEGCBNJr6UqRU3B4Q35rK8nAMsyPkrzka7HjJfOIxV063373x4YdaX62eoib/Miou9yBsNYPNT9zWk+jtpmljJ4hm+5eCd8OXeV/IHSJnW+3XtL+Te4V59AOiNDeuvbsGTWryIm+KBk/p+UBH0X36zcsWIY1DyFWIk60UlvyDI9UBqUmZ+IHLYqj6BerTOS0hDnkn3VyEzrSzu4xpohwgXC2HmsbEuXUmyc2yo9XuepufEsKzF2swZ+z64kwlr0EG6tjgNnHqy7RPl5TukB496Q="
 
 
 before_install:
+    # Fast finish the PR.
+    - |
+      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
+          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1
+
     # Remove homebrew.
-    - brew remove --force $(brew list)
-    - brew cleanup -s
-    - rm -rf $(brew --cache)
+    - |
+      echo ""
+      echo "Removing homebrew from Travis CI to avoid conflicts."
+      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
+      chmod +x ~/uninstall_homebrew
+      ~/uninstall_homebrew -fq
+      rm ~/uninstall_homebrew
+
 
 install:
+    # Install Miniconda.
     - |
+      echo ""
+      echo "Installing a fresh version of Miniconda."
       MINICONDA_URL="https://repo.continuum.io/miniconda"
       MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
       curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
       bash $MINICONDA_FILE -b
 
+    # Configure conda.
+    - |
+      echo ""
+      echo "Configuring conda."
       source /Users/travis/miniconda3/bin/activate root
-      conda config --add channels conda-forge
-      conda config --set show_channel_urls true
-      conda install --yes --quiet conda-forge-build-setup
+
+      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
+      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml
+
       source run_conda_forge_build_setup
 
-script:
-  - conda build ./recipe
+    # compiler cleanup
+    - |
+      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml
 
-  - upload_or_check_non_existence ./recipe conda-forge --channel=main
+script:
+  # generate the build number clobber
+  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
+  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
+  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
